---
application:
  name: "camouflage"
  project: "camouflage"
  organization: "QoveryCommunity"
  storage:
  - name: "/app"
    size: "10"
    type: "ssd"
    mount_point: "/mnt//app"
routers:
- name: "main-camouflage"
  routes:
  - application_name: "camouflage"
    paths:
    - "/*"
