version: "2.1"

services:
  camouflage:
    image: shubhendumadhukar/camouflage:latest
    container_name: camouflage
    volumes:
      - ./certs:/app/certs
      - ./mocks:/app/mocks
      - ./grpc:/app/grpc
      - ./config.yml:/app/config.yml
    expose:
      - 8080
      - 8443
      - 8081
      - 4312
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8081:8081"
      - "4312:4312"

