site_name: Camouflage
site_author: Shubhendu Madhukar
repo_url: https://github.com/fauxauldrich/camouflage
theme:
  name: material
markdown_extensions:
  - admonition
  - attr_list
nav:
  - index.md
  - getting-started.md
  - folder-structure.md
  - handlebars.md
  - request-matching.md
  - request-model.md
  - response-delays.md
  - performance-mode.md
  - monitoring.md
  - tests.md
  - releases.md
  - future-plans.md

